# Generated by Django 5.2.3 on 2025-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='core.project'),
        ),
    ]
