# Generated by Django 5.2.3 on 2025-06-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_skill_project_project_github_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_major',
            field=models.BooleanField(default=False),
        ),
    ]
