# Generated by Django 5.2.3 on 2025-06-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_is_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='title',
        ),
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
