# Generated by Django 5.2.3 on 2025-06-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_process_title_process_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessStep',
            new_name='Step',
        ),
    ]
