# Generated by Django 5.2.3 on 2025-06-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_processstep_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='core.process'),
        ),
    ]
