# Generated by Django 5.2.3 on 2025-06-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_step_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoitem',
            name='get_in_touch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_items', to='core.getintouch'),
        ),
    ]
