# Generated by Django 5.2.3 on 2025-06-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_infoitem_get_in_touch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='get_in_touch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_links', to='core.getintouch'),
        ),
    ]
