# Generated by Django 5.2.3 on 2025-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sociallink_get_in_touch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.BooleanField(default=True)),
                ('projects', models.BooleanField(default=True)),
                ('skills', models.BooleanField(default=True)),
                ('process', models.BooleanField(default=True)),
                ('get_in_touch', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sections',
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
