# Generated by Django 5.2.3 on 2025-06-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_project_options_rename_url_project_demo_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='svg_logo',
            new_name='logo_charecter',
        ),
    ]
